### ISSUE TITLE
Are we eventually building a React front-end for this project? 

### ISSUE THREAD

**Issue by farleyknight** [kasiaekiert/doctor#10]
If we are, we should discuss those details. I think the best way to add React is piece by piece, not to rewrite the entire front-end all at once. We should evaluate which pieces would benefit the most from a React interface, and then use the `react_on_rails` to include the components only where needed.

**Comment by kasiaekiert** [comment]
close it?

**Comment by farleyknight** [comment]
Yea, feel free to close all of the tickets that we already talked about or worked  on.
