### ISSUE TITLE
Polish up shopping cart experience?

### ISSUE THREAD

**Issue by farleyknight** [kasiaekiert/doctor#16]
I did a write-up with React and Stripe that we went through. However, it only allows for doing a payment through Stripe. One thing I wanted to do was to polish up the interface so we could begin adding products and allow users to order things. What do you think? Good idea? Maybe work on something else instead?

**Comment by kasiaekiert** [comment]
Yep, I have to recall how to use react - so I will work on it today. Thanks :D

**Comment by farleyknight** [comment]
This is definitely still in progress, so it's no longer a question but a task. I will close this but open up more related issues.
