### ISSUE TITLE
Add pry and pry-stack_explorer to the Gemfile

### ISSUE THREAD

**Issue by farleyknight** [kasiaekiert/doctor#2]
Experienced Rails developers use `pry` on a regular basis. Any time a software defect appears that is not immediately fixable will require an investigation. In those scenarios, it is important to have `pry` on hand.

In addition to the basic `pry`  functionality, I highly recommend `pry-stack_explorer` because it lets you move up and down the stack. If you have `method_1` which calls `method_2` which calls `method_3`, and the bug might be happening in `method_3` but the source of the problem is in `method_1` so you can use the stack explorer to move "up" the stack from `method_3` to `method_2` and then `method_1`, where you  can investigate the bug more closely.

I think I have talked a lot about this topic and maybe I can make it more clear with a good blog post :) Feel free to raise further questions here.

**Comment by kasiaekiert** [comment]
I have question, about that: 
https://github.com/pry/pry-stack_explorer

Can we setup these 2 gems that we don`t have to use "require 'pry-stack_explorer'" "require 'pry'" ?? 

Gems added

**Comment by farleyknight** [comment]
I don't think you should have to use `require 'pry'`? Feel free to add it to the `Gemfile` and I will check.  But it's never been a problem in the past for me.

**Comment by farleyknight** [comment]
This was where I added `pry`:

```ruby
group :development, :test do
  gem 'pry'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
end
```

**Comment by farleyknight** [comment]
Seems fine to me:

```shell
$ rails console
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Running via Spring preloader in process 4857
Loading development environment (Rails 6.0.2.1)
2.5.1 :001 >
2.5.1 :002 >
2.5.1 :003 > binding.pry
[1] pry(main)>
 => nil
2.5.1 :004 >
```

**Comment by farleyknight** [comment]
@kasiaekiert If this works for you, you can close this ticket.
